# Generated by Django 5.2.7 on 2025-10-31 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='gerente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.rol'),
        ),
    ]
